import '@/styles/globals.css'
import React from 'react'
import { type Metadata } from 'next'
import { Geist } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { TRPCReactProvider } from '@/trpc/react'
import { SiteSwitcher } from '@/app/_components/DevTools'
import Profile from '@/app/_components/Profile'
import { auth } from '@/server/auth'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  return (
    <html lang='en' className={`${geist.variable}`}>
      <body>
        <SiteSwitcher />
        <SessionProvider session={session}>
          <Profile />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
