import '@/styles/globals.css'
import React from 'react'
import { type Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { TRPCReactProvider } from '@/trpc/react'
import { SiteSwitcher } from '@/app/_components/SiteSwitcher'
import Profile from '@/app/_components/Profile'
import { auth } from '@/server/auth'
import AppUIProvider from '@/app/_provider/AppUIProvider'
import { Toaster } from '@/components/ui'

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by Next App',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  return (
    <html lang='en' className={``}>
      <body>
        <Toaster position='top-right' />
        <SiteSwitcher />
        <SessionProvider session={session}>
          <Profile />
          <TRPCReactProvider>
            <AppUIProvider>{children}</AppUIProvider>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
